version: "3"

services:
  phoenix:
    build: .
    volumes:
      - ./src:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    env_file:
      - db.env
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data